context:
  name: zed
  version: "1.13.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/zed-industries/zed/archive/v${{ version }}.tar.gz
    sha256: 56de109b1496cf12e7436a0402751f613c4f2eec3d2d708e4f16d915c52b2916

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - cmake
    - if: osx and arm64
      then:
        - lld
    - if: win
      then:
        - sqlite
        - openssl
        - nasm
        - libssh2
        - libgit2
        - ucrt

  host:
    - if: linux
      then:
        - alsa-lib
        - curl
        - expat
        - fontconfig
        - freetype
        - glib
        - libxcb
        - openssl
        - sqlite
        - libvulkan-loader
        - vulkan-tools
        - wayland
        - zlib
        - zstd
        - clang
        - mold
        - cmake
        - xorg-libx11
        - xorg-xproto
        - xorg-kbproto
        - libxkbcommon
    - if: win
      then:
        - ninja
        - cmake
        - lld
        - nasm
        - ucrt

tests:
  - script:
      - zed --help
about:
  homepage: https://zed.dev/
  summary: Code at the speed of thought
  description: |
    Zed is a high-performance, multiplayer code editor from the creators of Atom and Tree-sitter.
  license: Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-GPL
    - THIRDPARTY.yml
  repository: https://github.com/zed-industries/zed

extra:
  recipe-maintainers:
    - lucascolley
    - Hofer-Julian
    - zelosleone
